// flow-typed signature: ed5a31b18e415f9517921a75bee871d0
// flow-typed version: <<STUB>>/babel-preset-latest-node_v^3.2.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-latest-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-latest-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-latest-node/lib/index' {
  declare module.exports: any;
}

declare module 'babel-preset-latest-node/lib/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-latest-node/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-latest-node/lib/index'>;
}
declare module 'babel-preset-latest-node/lib/index.test.js' {
  declare module.exports: $Exports<'babel-preset-latest-node/lib/index.test'>;
}
