// flow-typed signature: f2885a0ada7cf7695bc8fbcee3b83039
// flow-typed version: <<STUB>>/express-guard_v^1.0.2/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-guard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-guard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-guard/examples/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/accepts/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/array-flatten/array-flatten' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/body-parser/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/body-parser/lib/read' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/body-parser/lib/types/json' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/body-parser/lib/types/raw' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/body-parser/lib/types/text' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/body-parser/lib/types/urlencoded' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/bytes/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/content-disposition/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/content-type/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/cookie-signature/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/cookie/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/debug/karma.conf' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/debug/node' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/debug/src/browser' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/debug/src/debug' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/debug/src/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/debug/src/inspector-log' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/debug/src/node' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/depd/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/depd/lib/browser/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/depd/lib/compat/callsite-tostring' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/depd/lib/compat/event-listener-count' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/depd/lib/compat/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/destroy/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/ee-first/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/encodeurl/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/escape-html/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/etag/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/accepts/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/array-flatten/array-flatten' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/read' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/json' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/raw' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/text' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/urlencoded' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/bytes/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/content-disposition/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/content-type/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/cookie-signature/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/cookie/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/karma.conf' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/node' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/browser' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/debug' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/inspector-log' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/node' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/browser/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/callsite-tostring' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/event-listener-count' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/destroy/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ee-first/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/encodeurl/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/escape-html/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/etag/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/application' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/express' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/middleware/init' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/middleware/query' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/request' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/response' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/layer' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/route' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/utils' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/view' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/finalhandler/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/forwarded/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/fresh/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/http-errors/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/dbcs-codec' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/dbcs-data' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/internal' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-codec' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data-generated' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/utf16' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/utf7' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/bom-handling' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/extend-node' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/streams' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/inherits/inherits_browser' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/inherits/inherits' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr.js/ipaddr.min' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr.js/lib/ipaddr' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/media-typer/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/merge-descriptors/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/methods/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime-db/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime-types/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/build/build' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/build/test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/cli' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/mime' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ms/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/charset' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/encoding' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/language' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/mediaType' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/on-finished/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/parseurl/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/path-to-regexp/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/proxy-addr/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/dist/qs' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/formats' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/parse' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/stringify' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/utils' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/parse' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/stringify' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/utils' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/range-parser/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/raw-body/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/safe-buffer/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/safe-buffer/test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/send/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/serve-static/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/setprototypeof/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/statuses/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/type-is/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/unpipe/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/utils-merge/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/vary/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/lib/common' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/lib/Guard' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/lib/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/lib/Role' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/lib/RoleList' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/common/common.hasDuplicate.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/guard/guard.constructor.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/guard/guard.requireAny.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/guard/guard.roles.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/role/role.checkRole.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/role/role.constructor.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/role/role.features.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/role/role.func.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/role/role.isValidRole.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/role/role.name.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.addManyRoles.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.addRole.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.checkRoles.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.constructor.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.getRole.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.getters.setters.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.rolesByAllowedFeatures.test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/application' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/express' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/middleware/init' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/middleware/query' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/request' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/response' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/router/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/router/layer' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/router/route' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/utils' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/express/lib/view' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/finalhandler/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/forwarded/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/fresh/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/http-errors/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/dbcs-codec' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/dbcs-data' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/internal' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-codec' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data-generated' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/utf16' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/encodings/utf7' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/lib/bom-handling' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/lib/extend-node' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/lib/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/iconv-lite/lib/streams' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/inherits/inherits_browser' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/inherits/inherits' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/ipaddr' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/ipaddr.js/ipaddr.min' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/ipaddr.js/lib/ipaddr' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/media-typer/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/merge-descriptors/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/methods/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/mime-db/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/mime-types/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/mime/build/build' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/mime/build/test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/mime/cli' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/mime/mime' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/ms/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/negotiator/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/negotiator/lib/charset' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/negotiator/lib/encoding' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/negotiator/lib/language' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/negotiator/lib/mediaType' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/on-finished/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/parseurl/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/path-to-regexp/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/proxy-addr/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/dist/qs' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/lib/formats' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/lib/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/lib/parse' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/lib/stringify' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/lib/utils' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/test/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/test/parse' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/test/stringify' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/qs/test/utils' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/range-parser/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/raw-body/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/safe-buffer/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/safe-buffer/test' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/send/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/serve-static/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/setprototypeof/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/statuses/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/type-is/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/unpipe/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/utils-merge/index' {
  declare module.exports: any;
}

declare module 'express-guard/examples/node_modules/vary/index' {
  declare module.exports: any;
}

declare module 'express-guard/lib/common' {
  declare module.exports: any;
}

declare module 'express-guard/lib/Guard' {
  declare module.exports: any;
}

declare module 'express-guard/lib/index' {
  declare module.exports: any;
}

declare module 'express-guard/lib/Role' {
  declare module.exports: any;
}

declare module 'express-guard/lib/RoleList' {
  declare module.exports: any;
}

declare module 'express-guard/test/common/common.hasDuplicate.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/guard/guard.constructor.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/guard/guard.requireAny.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/guard/guard.roles.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/role/role.checkRole.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/role/role.constructor.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/role/role.features.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/role/role.func.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/role/role.isValidRole.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/role/role.name.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/roleList/roleList.addManyRoles.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/roleList/roleList.addRole.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/roleList/roleList.checkRoles.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/roleList/roleList.constructor.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/roleList/roleList.getRole.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/roleList/roleList.getters.setters.test' {
  declare module.exports: any;
}

declare module 'express-guard/test/roleList/roleList.rolesByAllowedFeatures.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-guard/examples/index.js' {
  declare module.exports: $Exports<'express-guard/examples/index'>;
}
declare module 'express-guard/examples/node_modules/accepts/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/accepts/index'>;
}
declare module 'express-guard/examples/node_modules/array-flatten/array-flatten.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/array-flatten/array-flatten'>;
}
declare module 'express-guard/examples/node_modules/body-parser/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/body-parser/index'>;
}
declare module 'express-guard/examples/node_modules/body-parser/lib/read.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/body-parser/lib/read'>;
}
declare module 'express-guard/examples/node_modules/body-parser/lib/types/json.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/body-parser/lib/types/json'>;
}
declare module 'express-guard/examples/node_modules/body-parser/lib/types/raw.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/body-parser/lib/types/raw'>;
}
declare module 'express-guard/examples/node_modules/body-parser/lib/types/text.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/body-parser/lib/types/text'>;
}
declare module 'express-guard/examples/node_modules/body-parser/lib/types/urlencoded.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/body-parser/lib/types/urlencoded'>;
}
declare module 'express-guard/examples/node_modules/bytes/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/bytes/index'>;
}
declare module 'express-guard/examples/node_modules/content-disposition/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/content-disposition/index'>;
}
declare module 'express-guard/examples/node_modules/content-type/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/content-type/index'>;
}
declare module 'express-guard/examples/node_modules/cookie-signature/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/cookie-signature/index'>;
}
declare module 'express-guard/examples/node_modules/cookie/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/cookie/index'>;
}
declare module 'express-guard/examples/node_modules/debug/karma.conf.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/debug/karma.conf'>;
}
declare module 'express-guard/examples/node_modules/debug/node.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/debug/node'>;
}
declare module 'express-guard/examples/node_modules/debug/src/browser.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/debug/src/browser'>;
}
declare module 'express-guard/examples/node_modules/debug/src/debug.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/debug/src/debug'>;
}
declare module 'express-guard/examples/node_modules/debug/src/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/debug/src/index'>;
}
declare module 'express-guard/examples/node_modules/debug/src/inspector-log.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/debug/src/inspector-log'>;
}
declare module 'express-guard/examples/node_modules/debug/src/node.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/debug/src/node'>;
}
declare module 'express-guard/examples/node_modules/depd/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/depd/index'>;
}
declare module 'express-guard/examples/node_modules/depd/lib/browser/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/depd/lib/browser/index'>;
}
declare module 'express-guard/examples/node_modules/depd/lib/compat/callsite-tostring.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/depd/lib/compat/callsite-tostring'>;
}
declare module 'express-guard/examples/node_modules/depd/lib/compat/event-listener-count.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/depd/lib/compat/event-listener-count'>;
}
declare module 'express-guard/examples/node_modules/depd/lib/compat/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/depd/lib/compat/index'>;
}
declare module 'express-guard/examples/node_modules/destroy/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/destroy/index'>;
}
declare module 'express-guard/examples/node_modules/ee-first/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/ee-first/index'>;
}
declare module 'express-guard/examples/node_modules/encodeurl/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/encodeurl/index'>;
}
declare module 'express-guard/examples/node_modules/escape-html/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/escape-html/index'>;
}
declare module 'express-guard/examples/node_modules/etag/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/etag/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/accepts/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/accepts/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/array-flatten/array-flatten.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/array-flatten/array-flatten'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/read.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/read'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/json.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/json'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/raw.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/raw'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/text.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/text'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/urlencoded.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/body-parser/lib/types/urlencoded'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/bytes/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/bytes/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/content-disposition/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/content-disposition/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/content-type/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/content-type/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/cookie-signature/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/cookie-signature/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/cookie/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/cookie/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/karma.conf.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/karma.conf'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/node.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/node'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/browser.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/browser'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/debug.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/debug'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/inspector-log.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/inspector-log'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/node.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/debug/src/node'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/browser/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/browser/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/callsite-tostring.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/callsite-tostring'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/event-listener-count.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/event-listener-count'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/depd/lib/compat/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/destroy/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/destroy/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ee-first/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/ee-first/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/encodeurl/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/encodeurl/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/escape-html/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/escape-html/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/etag/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/etag/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/application.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/application'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/express.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/express'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/middleware/init.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/middleware/init'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/middleware/query.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/middleware/query'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/request.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/request'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/response.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/response'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/layer.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/layer'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/route.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/router/route'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/utils.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/utils'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/view.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/express/lib/view'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/finalhandler/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/finalhandler/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/forwarded/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/forwarded/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/fresh/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/fresh/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/http-errors/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/http-errors/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/dbcs-codec.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/dbcs-codec'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/dbcs-data.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/dbcs-data'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/internal.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/internal'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-codec.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-codec'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data-generated.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data-generated'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/utf16.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/utf16'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/utf7.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/encodings/utf7'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/bom-handling.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/bom-handling'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/extend-node.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/extend-node'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/streams.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/iconv-lite/lib/streams'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/inherits/inherits_browser.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/inherits/inherits_browser'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/inherits/inherits.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/inherits/inherits'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr.js/ipaddr.min.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr.js/ipaddr.min'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr.js/lib/ipaddr.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/ipaddr.js/lib/ipaddr'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/media-typer/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/media-typer/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/merge-descriptors/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/merge-descriptors/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/methods/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/methods/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime-db/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/mime-db/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime-types/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/mime-types/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/build/build.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/build/build'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/build/test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/build/test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/cli.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/cli'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/mime.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/mime/mime'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/ms/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/ms/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/charset.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/charset'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/encoding.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/encoding'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/language.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/language'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/mediaType.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/negotiator/lib/mediaType'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/on-finished/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/on-finished/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/parseurl/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/parseurl/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/path-to-regexp/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/path-to-regexp/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/proxy-addr/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/proxy-addr/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/dist/qs.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/dist/qs'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/formats.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/formats'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/parse.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/parse'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/stringify.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/stringify'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/utils.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/lib/utils'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/parse.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/parse'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/stringify.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/stringify'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/utils.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/qs/test/utils'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/range-parser/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/range-parser/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/raw-body/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/raw-body/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/safe-buffer/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/safe-buffer/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/safe-buffer/test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/safe-buffer/test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/send/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/send/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/serve-static/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/serve-static/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/setprototypeof/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/setprototypeof/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/statuses/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/statuses/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/type-is/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/type-is/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/unpipe/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/unpipe/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/utils-merge/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/utils-merge/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/examples/node_modules/vary/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/examples/node_modules/vary/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/lib/common.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/lib/common'>;
}
declare module 'express-guard/examples/node_modules/express-guard/lib/Guard.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/lib/Guard'>;
}
declare module 'express-guard/examples/node_modules/express-guard/lib/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/lib/index'>;
}
declare module 'express-guard/examples/node_modules/express-guard/lib/Role.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/lib/Role'>;
}
declare module 'express-guard/examples/node_modules/express-guard/lib/RoleList.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/lib/RoleList'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/common/common.hasDuplicate.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/common/common.hasDuplicate.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/guard/guard.constructor.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/guard/guard.constructor.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/guard/guard.requireAny.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/guard/guard.requireAny.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/guard/guard.roles.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/guard/guard.roles.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/role/role.checkRole.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/role/role.checkRole.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/role/role.constructor.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/role/role.constructor.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/role/role.features.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/role/role.features.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/role/role.func.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/role/role.func.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/role/role.isValidRole.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/role/role.isValidRole.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/role/role.name.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/role/role.name.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.addManyRoles.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/roleList/roleList.addManyRoles.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.addRole.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/roleList/roleList.addRole.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.checkRoles.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/roleList/roleList.checkRoles.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.constructor.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/roleList/roleList.constructor.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.getRole.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/roleList/roleList.getRole.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.getters.setters.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/roleList/roleList.getters.setters.test'>;
}
declare module 'express-guard/examples/node_modules/express-guard/test/roleList/roleList.rolesByAllowedFeatures.test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express-guard/test/roleList/roleList.rolesByAllowedFeatures.test'>;
}
declare module 'express-guard/examples/node_modules/express/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/index'>;
}
declare module 'express-guard/examples/node_modules/express/lib/application.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/application'>;
}
declare module 'express-guard/examples/node_modules/express/lib/express.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/express'>;
}
declare module 'express-guard/examples/node_modules/express/lib/middleware/init.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/middleware/init'>;
}
declare module 'express-guard/examples/node_modules/express/lib/middleware/query.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/middleware/query'>;
}
declare module 'express-guard/examples/node_modules/express/lib/request.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/request'>;
}
declare module 'express-guard/examples/node_modules/express/lib/response.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/response'>;
}
declare module 'express-guard/examples/node_modules/express/lib/router/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/router/index'>;
}
declare module 'express-guard/examples/node_modules/express/lib/router/layer.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/router/layer'>;
}
declare module 'express-guard/examples/node_modules/express/lib/router/route.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/router/route'>;
}
declare module 'express-guard/examples/node_modules/express/lib/utils.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/utils'>;
}
declare module 'express-guard/examples/node_modules/express/lib/view.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/express/lib/view'>;
}
declare module 'express-guard/examples/node_modules/finalhandler/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/finalhandler/index'>;
}
declare module 'express-guard/examples/node_modules/forwarded/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/forwarded/index'>;
}
declare module 'express-guard/examples/node_modules/fresh/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/fresh/index'>;
}
declare module 'express-guard/examples/node_modules/http-errors/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/http-errors/index'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/dbcs-codec.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/dbcs-codec'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/dbcs-data.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/dbcs-data'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/index'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/internal.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/internal'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-codec.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-codec'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data-generated.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data-generated'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/sbcs-data'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/utf16.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/utf16'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/encodings/utf7.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/encodings/utf7'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/lib/bom-handling.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/lib/bom-handling'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/lib/extend-node.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/lib/extend-node'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/lib/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/lib/index'>;
}
declare module 'express-guard/examples/node_modules/iconv-lite/lib/streams.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/iconv-lite/lib/streams'>;
}
declare module 'express-guard/examples/node_modules/inherits/inherits_browser.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/inherits/inherits_browser'>;
}
declare module 'express-guard/examples/node_modules/inherits/inherits.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/inherits/inherits'>;
}
declare module 'express-guard/examples/node_modules/ipaddr.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/ipaddr'>;
}
declare module 'express-guard/examples/node_modules/ipaddr.js/ipaddr.min.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/ipaddr.js/ipaddr.min'>;
}
declare module 'express-guard/examples/node_modules/ipaddr.js/lib/ipaddr.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/ipaddr.js/lib/ipaddr'>;
}
declare module 'express-guard/examples/node_modules/media-typer/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/media-typer/index'>;
}
declare module 'express-guard/examples/node_modules/merge-descriptors/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/merge-descriptors/index'>;
}
declare module 'express-guard/examples/node_modules/methods/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/methods/index'>;
}
declare module 'express-guard/examples/node_modules/mime-db/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/mime-db/index'>;
}
declare module 'express-guard/examples/node_modules/mime-types/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/mime-types/index'>;
}
declare module 'express-guard/examples/node_modules/mime/build/build.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/mime/build/build'>;
}
declare module 'express-guard/examples/node_modules/mime/build/test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/mime/build/test'>;
}
declare module 'express-guard/examples/node_modules/mime/cli.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/mime/cli'>;
}
declare module 'express-guard/examples/node_modules/mime/mime.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/mime/mime'>;
}
declare module 'express-guard/examples/node_modules/ms/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/ms/index'>;
}
declare module 'express-guard/examples/node_modules/negotiator/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/negotiator/index'>;
}
declare module 'express-guard/examples/node_modules/negotiator/lib/charset.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/negotiator/lib/charset'>;
}
declare module 'express-guard/examples/node_modules/negotiator/lib/encoding.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/negotiator/lib/encoding'>;
}
declare module 'express-guard/examples/node_modules/negotiator/lib/language.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/negotiator/lib/language'>;
}
declare module 'express-guard/examples/node_modules/negotiator/lib/mediaType.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/negotiator/lib/mediaType'>;
}
declare module 'express-guard/examples/node_modules/on-finished/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/on-finished/index'>;
}
declare module 'express-guard/examples/node_modules/parseurl/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/parseurl/index'>;
}
declare module 'express-guard/examples/node_modules/path-to-regexp/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/path-to-regexp/index'>;
}
declare module 'express-guard/examples/node_modules/proxy-addr/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/proxy-addr/index'>;
}
declare module 'express-guard/examples/node_modules/qs/dist/qs.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/dist/qs'>;
}
declare module 'express-guard/examples/node_modules/qs/lib/formats.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/lib/formats'>;
}
declare module 'express-guard/examples/node_modules/qs/lib/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/lib/index'>;
}
declare module 'express-guard/examples/node_modules/qs/lib/parse.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/lib/parse'>;
}
declare module 'express-guard/examples/node_modules/qs/lib/stringify.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/lib/stringify'>;
}
declare module 'express-guard/examples/node_modules/qs/lib/utils.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/lib/utils'>;
}
declare module 'express-guard/examples/node_modules/qs/test/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/test/index'>;
}
declare module 'express-guard/examples/node_modules/qs/test/parse.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/test/parse'>;
}
declare module 'express-guard/examples/node_modules/qs/test/stringify.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/test/stringify'>;
}
declare module 'express-guard/examples/node_modules/qs/test/utils.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/qs/test/utils'>;
}
declare module 'express-guard/examples/node_modules/range-parser/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/range-parser/index'>;
}
declare module 'express-guard/examples/node_modules/raw-body/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/raw-body/index'>;
}
declare module 'express-guard/examples/node_modules/safe-buffer/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/safe-buffer/index'>;
}
declare module 'express-guard/examples/node_modules/safe-buffer/test.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/safe-buffer/test'>;
}
declare module 'express-guard/examples/node_modules/send/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/send/index'>;
}
declare module 'express-guard/examples/node_modules/serve-static/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/serve-static/index'>;
}
declare module 'express-guard/examples/node_modules/setprototypeof/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/setprototypeof/index'>;
}
declare module 'express-guard/examples/node_modules/statuses/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/statuses/index'>;
}
declare module 'express-guard/examples/node_modules/type-is/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/type-is/index'>;
}
declare module 'express-guard/examples/node_modules/unpipe/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/unpipe/index'>;
}
declare module 'express-guard/examples/node_modules/utils-merge/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/utils-merge/index'>;
}
declare module 'express-guard/examples/node_modules/vary/index.js' {
  declare module.exports: $Exports<'express-guard/examples/node_modules/vary/index'>;
}
declare module 'express-guard/lib/common.js' {
  declare module.exports: $Exports<'express-guard/lib/common'>;
}
declare module 'express-guard/lib/Guard.js' {
  declare module.exports: $Exports<'express-guard/lib/Guard'>;
}
declare module 'express-guard/lib/index.js' {
  declare module.exports: $Exports<'express-guard/lib/index'>;
}
declare module 'express-guard/lib/Role.js' {
  declare module.exports: $Exports<'express-guard/lib/Role'>;
}
declare module 'express-guard/lib/RoleList.js' {
  declare module.exports: $Exports<'express-guard/lib/RoleList'>;
}
declare module 'express-guard/test/common/common.hasDuplicate.test.js' {
  declare module.exports: $Exports<'express-guard/test/common/common.hasDuplicate.test'>;
}
declare module 'express-guard/test/guard/guard.constructor.test.js' {
  declare module.exports: $Exports<'express-guard/test/guard/guard.constructor.test'>;
}
declare module 'express-guard/test/guard/guard.requireAny.test.js' {
  declare module.exports: $Exports<'express-guard/test/guard/guard.requireAny.test'>;
}
declare module 'express-guard/test/guard/guard.roles.test.js' {
  declare module.exports: $Exports<'express-guard/test/guard/guard.roles.test'>;
}
declare module 'express-guard/test/role/role.checkRole.test.js' {
  declare module.exports: $Exports<'express-guard/test/role/role.checkRole.test'>;
}
declare module 'express-guard/test/role/role.constructor.test.js' {
  declare module.exports: $Exports<'express-guard/test/role/role.constructor.test'>;
}
declare module 'express-guard/test/role/role.features.test.js' {
  declare module.exports: $Exports<'express-guard/test/role/role.features.test'>;
}
declare module 'express-guard/test/role/role.func.test.js' {
  declare module.exports: $Exports<'express-guard/test/role/role.func.test'>;
}
declare module 'express-guard/test/role/role.isValidRole.test.js' {
  declare module.exports: $Exports<'express-guard/test/role/role.isValidRole.test'>;
}
declare module 'express-guard/test/role/role.name.test.js' {
  declare module.exports: $Exports<'express-guard/test/role/role.name.test'>;
}
declare module 'express-guard/test/roleList/roleList.addManyRoles.test.js' {
  declare module.exports: $Exports<'express-guard/test/roleList/roleList.addManyRoles.test'>;
}
declare module 'express-guard/test/roleList/roleList.addRole.test.js' {
  declare module.exports: $Exports<'express-guard/test/roleList/roleList.addRole.test'>;
}
declare module 'express-guard/test/roleList/roleList.checkRoles.test.js' {
  declare module.exports: $Exports<'express-guard/test/roleList/roleList.checkRoles.test'>;
}
declare module 'express-guard/test/roleList/roleList.constructor.test.js' {
  declare module.exports: $Exports<'express-guard/test/roleList/roleList.constructor.test'>;
}
declare module 'express-guard/test/roleList/roleList.getRole.test.js' {
  declare module.exports: $Exports<'express-guard/test/roleList/roleList.getRole.test'>;
}
declare module 'express-guard/test/roleList/roleList.getters.setters.test.js' {
  declare module.exports: $Exports<'express-guard/test/roleList/roleList.getters.setters.test'>;
}
declare module 'express-guard/test/roleList/roleList.rolesByAllowedFeatures.test.js' {
  declare module.exports: $Exports<'express-guard/test/roleList/roleList.rolesByAllowedFeatures.test'>;
}
