// flow-typed signature: 76f778a36f570ea665832ad657ef84fd
// flow-typed version: <<STUB>>/knex-migrate_v^1.7.2/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'knex-migrate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'knex-migrate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'knex-migrate/src/cli' {
  declare module.exports: any;
}

declare module 'knex-migrate/src/index' {
  declare module.exports: any;
}

declare module 'knex-migrate/src/index.test' {
  declare module.exports: any;
}

declare module 'knex-migrate/src/storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'knex-migrate/src/cli.js' {
  declare module.exports: $Exports<'knex-migrate/src/cli'>;
}
declare module 'knex-migrate/src/index.js' {
  declare module.exports: $Exports<'knex-migrate/src/index'>;
}
declare module 'knex-migrate/src/index.test.js' {
  declare module.exports: $Exports<'knex-migrate/src/index.test'>;
}
declare module 'knex-migrate/src/storage.js' {
  declare module.exports: $Exports<'knex-migrate/src/storage'>;
}
