// flow-typed signature: 7a020b27b43ab5f9855de8ff51d16363
// flow-typed version: <<STUB>>/morgan-body_v^2.4.7/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'morgan-body'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'morgan-body' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'morgan-body/index' {
  declare module.exports: $Exports<'morgan-body'>;
}
declare module 'morgan-body/index.js' {
  declare module.exports: $Exports<'morgan-body'>;
}
