// flow-typed signature: 7e5710db3ece129ed190f85b8ad58d3a
// flow-typed version: <<STUB>>/scrypt-kdf_v^2.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrypt-kdf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrypt-kdf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scrypt-kdf/scrypt' {
  declare module.exports: any;
}

declare module 'scrypt-kdf/test/scrypt-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scrypt-kdf/scrypt.js' {
  declare module.exports: $Exports<'scrypt-kdf/scrypt'>;
}
declare module 'scrypt-kdf/test/scrypt-tests.js' {
  declare module.exports: $Exports<'scrypt-kdf/test/scrypt-tests'>;
}
